// examples/next/components/ui/button.tsx
import React from "react";
import { cn } from "@/lib/utils";

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
	className?: string;
	children?: React.ReactNode;
}

const Button: React.FC<ButtonProps> = ({ className, children, ...props }) => {
	return (
		<button className={cn("bg-red-500 text-white font-bold size-20 rounded-full", className)} {...props}>
			{children}
		</button>
	);
};

export default Button;

// examples/sveltekit/src/lib/components/ui/button/button.svelte
<script lang="ts">
	import { cn } from '$lib/utils/utils';
    import { type WithChildren } from 'bits-ui'

    type Props = {
        class?: string;
    }

    let { class: className, children }: WithChildren<Props> = $props();
</script>

<button class={cn("bg-red-500 text-white font-bold size-20 rounded-full",className)}>
    {@render children?.()}
</button>
